environment:
  adminEmail: yvan.aquino@cloud-colosseum.net
  domain: cloud-colosseum.net
  projectId: holy-diver-297719
  scopes:
  - https://www.googleapis.com/auth/admin.reports.audit.readonly
  - https://www.googleapis.com/auth/admin.reports.usage.readonly
  - https://www.googleapis.com/auth/admin.directory.user.readonly
  - https://www.googleapis.com/auth/classroom.courses.readonly
  - https://www.googleapis.com/auth/classroom.coursework.students.readonly
  - https://www.googleapis.com/auth/gmail.readonly
  serviceAccountKey: service.json
  services:
    bigquery:
      datasetId: jobcorps
      bigqueryBatchSize: 500
resources:
  meets:
    method_parameters:
      applicationName: meet
      maxResults: 500
      userKey: all
    tableId: meets
  calendar:
    method_parameters:
      applicationName: calendar
      maxResults: 500
      userKey: all
    tableId: calendar
  login:
    method_parameters:
      applicationName: login
      maxResults: 500
      userKey: all
    tableId: login
  user_accounts:
    method_parameters:
      applicationName: user_accounts
      maxResults: 500
      userKey: all
    tableId: user_accounts
  chat:
    method_parameters:
      applicationName: chat
      maxResults: 500
      userKey: all
    tableId: chat
  drive:
    method_parameters:
      applicationName: drive
      maxResults: 500
      userKey: all
    tableId: drive
  userUsage:
    method_parameters:
      date: null
      maxResults: 500
      userKey: all
    tableId: userUsage
  users:
    method_parameters:
      domain: cloud-colosseum.net
      maxResults: 500
      orderBy: email
    tableId: users
  courses:
    method_parameters:
      pageSize: 500
      studentId: null
      teacherId: null
    tableId: courses
  courseWork:
    method_parameters:
      courseId: null
      pageSize: 500
      orderBy: updateTime desc
    tableId: courseWork
  gmailUserProfiles:
    method_parameters:
      userId: me
    tableId: gmailUserProfiles